### ISSUE TITLE
Router and redirect

### ISSUE THREAD

**Issue by pedromvieira** [smeevil/set_locale#6]
I'm trying to implement this plug with several scopes levels in router.
After place "/:locale/users" ("/users" before), on templates and controllers how to use conn redirect to user_path?

Before: conn |> redirect(to: user_path,  action, options)

**Comment by smeevil** [comment]
Hi,

I'm not sure what you mean. You should be abel to use redirects as you would do normally and the path will be automatically be rewritten to prefix the correct locale.

Gerard.

**Comment by pedromvieira** [comment]
If I plug Set locale, set dummy "/" scope and place "/:locale" before each other scope my router can't find paths (neither I can test mix phx.routes).
Is something else to setup? (scope_path redirects, like user_path cannot be founded).

**Comment by smeevil** [comment]
The path helpers would require a locale as third argument, and options are given as fourth. 
example : `page_path(@conn, :home, @locale, options)`
Could you try this ?

**Comment by pedromvieira** [comment]
I used a combination of params["locale"] (controllers) and @conn.params["locale"] (templates) but got stucked at my redirect for my first page (authentication) with:

Controller.init/1 (I dont have any init declared on my controllers without set_locale)

```
Request: GET /en/auth/identity
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function Auth.UeberauthController.init/1 is undefined (module Auth.UeberauthController is not available)
        Auth.UeberauthController.init(:request)
        (phishx) lib/phishx_web/router.ex:1: anonymous fn/1 in PhishxWeb.Router.__match_route__/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (phishx) lib/phishx_web/endpoint.ex:1: PhishxWeb.Endpoint.plug_builder_call/2
        (phishx) lib/plug/debugger.ex:99: PhishxWeb.Endpoint."call (overridable 3)"/2
        (phishx) lib/phishx_web/endpoint.ex:1: PhishxWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /home/vieira/ownCloud/ELIXIR_PHOENIX/phishx/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by pedromvieira** [comment]
OK. Worked only with params["locale"] on Controllers and @locale elsewhere (Templates).
If I tried @locae at controllers, returns nil.
So in your example on a Controller perspective : 
```
page_path(@conn, :home, params["locale"], options) # ok
page_path(@conn, :home, @locale, options) # nil / error
```
